# SQL

## Loading a database
1. in your terminal, navigate to the folder containing the databasename.sql file
2. psql to enter the postgres terminal
3. CREATE DATABASE databasename; where databasename is the name of the database
4. \q to exit the postgres terminal
5. psql databasename < databasename.sql to load the database
6. psql databasename to log in to the database and start SQLing!!

### Let's just use the CITY table. Write a query for the following:

##### Quit psql:
\q

##### Show tables:
\d

##### Show first 10 rows of a table
SELECT * FROM city LIMIT 10;

##### What is the total world population?
SELECT SUM(population) from city;

##### What is the population of each country?
SELECT countrycode, sum(population) from city group by countrycode limit 10;

##### What is the population of each country, ordered highest to lowest population?
SELECT countrycode, sum(population) from city group by countrycode order by 2 DESC limit 10;

##### What is the population of each country, ordered alphabetically?
SELECT countrycode, sum(population) from city group by 1 order by 1 limit 10;

# Pandas

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('hospital-costs.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383493 entries, 0 to 383492
Data columns (total 14 columns):
Year                                   383493 non-null int64
Facility Id                            383493 non-null int64
Facility Name                          383493 non-null object
APR DRG Code                           383493 non-null int64
APR Severity of Illness Code           383493 non-null int64
APR DRG Description                    383493 non-null object
APR Severity of Illness Description    383329 non-null object
APR Medical Surgical Code              383329 non-null object
APR Medical Surgical Description       383493 non-null object
Discharges                             383493 non-null int64
Mean Charge                            383493 non-null float64
Median Charge                          383493 non-null float64
Mean Cost                              383493 non-null float64
Median Cost                            383493 non-null float64
dtypes: float64(4), int64(5), object(5)
memory usage: 41.0+ MB

In [7]:
df.head()

,Year,Facility Id,Facility Name,APR DRG Code,APR Severity of Illness Code,APR DRG Description,APR Severity of Illness Description,APR Medical Surgical Code,APR Medical Surgical Description,Discharges,Mean Charge,Median Charge,Mean Cost,Median Cost
0,2011,324,Adirondack Medical Center-Saranac Lake Site,4,4,Tracheostomy W MV 96+ Hours W Extensive Proced...,Extreme,P,Surgical,3,361289.0,210882.0,196080.0,123347.0
1,2011,324,Adirondack Medical Center-Saranac Lake Site,5,4,Tracheostomy W MV 96+ Hours W/O Extensive Proc...,Extreme,P,Surgical,1,102190.0,102190.0,59641.0,59641.0
2,2011,324,Adirondack Medical Center-Saranac Lake Site,24,2,Extracranial Vascular Procedures,Moderate,P,Surgical,6,14172.0,13506.0,6888.0,6445.0
3,2011,324,Adirondack Medical Center-Saranac Lake Site,26,1,Other Nervous System & Related Procedures,Minor,P,Surgical,1,8833.0,8833.0,4259.0,4259.0
4,2011,324,Adirondack Medical Center-Saranac Lake Site,41,1,Nervous System Malignancy,Minor,M,Medical,1,5264.0,5264.0,1727.0,1727.0

In [9]:
# Add a new column 'Total Cost'
df['Total_Cost'] = df['Discharges'] * df['Mean Cost']
df.head()

,Year,Facility Id,Facility Name,APR DRG Code,APR Severity of Illness Code,APR DRG Description,APR Severity of Illness Description,APR Medical Surgical Code,APR Medical Surgical Description,Discharges,Mean Charge,Median Charge,Mean Cost,Median Cost,Total_Cost
0,2011,324,Adirondack Medical Center-Saranac Lake Site,4,4,Tracheostomy W MV 96+ Hours W Extensive Proced...,Extreme,P,Surgical,3,361289.0,210882.0,196080.0,123347.0,588240.0
1,2011,324,Adirondack Medical Center-Saranac Lake Site,5,4,Tracheostomy W MV 96+ Hours W/O Extensive Proc...,Extreme,P,Surgical,1,102190.0,102190.0,59641.0,59641.0,59641.0
2,2011,324,Adirondack Medical Center-Saranac Lake Site,24,2,Extracranial Vascular Procedures,Moderate,P,Surgical,6,14172.0,13506.0,6888.0,6445.0,41328.0
3,2011,324,Adirondack Medical Center-Saranac Lake Site,26,1,Other Nervous System & Related Procedures,Minor,P,Surgical,1,8833.0,8833.0,4259.0,4259.0,4259.0
4,2011,324,Adirondack Medical Center-Saranac Lake Site,41,1,Nervous System Malignancy,Minor,M,Medical,1,5264.0,5264.0,1727.0,1727.0,1727.0

In [13]:
# Group by facility name and get the total cost for each hospital
df.groupby(['Facility Name']).sum().head()

,Year,Facility Id,APR DRG Code,APR Severity of Illness Code,Discharges,Mean Charge,Median Charge,Mean Cost,Median Cost,Total_Cost
Facility Name,,,,,,,,,,
Adirondack Medical Center-Saranac Lake Site,2986846,481464,544477,3349,9105,27854270.0,26595453.0,14811317.0,14111541.0,7.742766e+07
Albany Medical Center - South Clinical Campus,100506,100,21440,77,121,786180.0,766091.0,665748.0,656873.0,1.432784e+06
Albany Medical Center Hospital,6564663,3266,1251911,7988,97105,191079985.0,174030239.0,64044338.0,56956503.0,1.336299e+09
Albany Memorial Hospital,3509446,6984,606081,4121,14114,34278912.0,32451673.0,15875883.0,14879268.0,9.490717e+07
Alice Hyde Medical Center,2697409,436150,503725,2925,10018,14889555.0,14166617.0,7054564.0,6699064.0,4.105882e+07

In [15]:
df.groupby('Facility Name').sum().reset_index().head()

,Facility Name,Year,Facility Id,APR DRG Code,APR Severity of Illness Code,Discharges,Mean Charge,Median Charge,Mean Cost,Median Cost,Total_Cost
0,Adirondack Medical Center-Saranac Lake Site,2986846,481464,544477,3349,9105,27854270.0,26595453.0,14811317.0,14111541.0,7.742766e+07
1,Albany Medical Center - South Clinical Campus,100506,100,21440,77,121,786180.0,766091.0,665748.0,656873.0,1.432784e+06
2,Albany Medical Center Hospital,6564663,3266,1251911,7988,97105,191079985.0,174030239.0,64044338.0,56956503.0,1.336299e+09
3,Albany Memorial Hospital,3509446,6984,606081,4121,14114,34278912.0,32451673.0,15875883.0,14879268.0,9.490717e+07
4,Alice Hyde Medical Center,2697409,436150,503725,2925,10018,14889555.0,14166617.0,7054564.0,6699064.0,4.105882e+07

In [16]:
df.groupby('Facility Name').sum()['Total_Cost'].head()

Facility Name
Adirondack Medical Center-Saranac Lake Site      7.742766e+07
Albany Medical Center - South Clinical Campus    1.432784e+06
Albany Medical Center Hospital                   1.336299e+09
Albany Memorial Hospital                         9.490717e+07
Alice Hyde Medical Center                        4.105882e+07
Name: Total_Cost, dtype: float64

In [17]:
df.groupby('Facility Name').sum().iloc[:,-1].head()

Facility Name
Adirondack Medical Center-Saranac Lake Site      7.742766e+07
Albany Medical Center - South Clinical Campus    1.432784e+06
Albany Medical Center Hospital                   1.336299e+09
Albany Memorial Hospital                         9.490717e+07
Alice Hyde Medical Center                        4.105882e+07
Name: Total_Cost, dtype: float64

In [20]:
df[['Facility Name', 'Total_Cost']].groupby('Facility Name').sum().reset_index().head()

                                   Facility Name    Total_Cost
0    Adirondack Medical Center-Saranac Lake Site  7.742766e+07
1  Albany Medical Center - South Clinical Campus  1.432784e+06
2                 Albany Medical Center Hospital  1.336299e+09
3                       Albany Memorial Hospital  9.490717e+07
4                      Alice Hyde Medical Center  4.105882e+07

In [21]:
df[['Facility Name', 'Total_Cost']].groupby('Facility Name').sum().reset_index().iloc[0,1]

77427664.0